### ISSUE TITLE
How to avoid collections being defined multiple times

### ISSUE THREAD

**Issue by scottspeidel** [handmadeadv/vector#8]
Hello handmadeadv,

I like the vector package. Thanks for making it. Unfortunately, I am having trouble with collections being defined twice if I add them to the settings.json file. 

for example say I have a pages collection as follows:

in pages.js
Pages = new Meteor.Collectionco("pages");

in settings.json

"pages": {
        "roles": ["administrator"],
        "collectionFields": [
          {
            "label": "Manage pages",
            "type": "list"
          }
... etc.

I get the following stack trace:

W2036-17:24:58.541(-5)? (STDERR) /Users/ss/.meteor/tools/0b2f28e18b/lib/node_modules/fibers/future.js:173
W2036-17:24:58.542(-5)? (STDERR)                        throw(ex);
W2036-17:24:58.542(-5)? (STDERR)                              ^
W2036-17:24:58.589(-5)? (STDERR) Error: A method named '/pages/insert' is already defined
W2036-17:24:58.589(-5)? (STDERR)     at packages/livedata/livedata_server.js:1174
W2036-17:24:58.589(-5)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:87)
W2036-17:24:58.590(-5)? (STDERR)     at _.extend.methods (packages/livedata/livedata_server.js:1172)
W2036-17:24:58.591(-5)? (STDERR)     at Meteor.Collection._defineMutationMethods (packages/mongo-livedata/collection.js:667)
W2036-17:24:58.591(-5)? (STDERR)     at new Meteor.Collection (packages/mongo-livedata/collection.js:176)
W2036-17:24:58.591(-5)? (STDERR)     at app/lib/collections/chronologs.js:7:9
W2036-17:24:58.592(-5)? (STDERR)     at app/lib/collections/chronologs.js:9:3
W2036-17:24:58.592(-5)? (STDERR)     at /Users/ss/code/crlg/.meteor/local/build/programs/server/boot.js:154:10
W2036-17:24:58.593(-5)? (STDERR)     at Array.forEach (native)
W2036-17:24:58.593(-5)? (STDERR)     at Function._.each._.forEach (/Users/ss/.meteor/tools/0b2f28e18b/lib/node_modules/underscore/underscore.js:79:11)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

What would you recommend?

**Comment by handmadeadv** [comment]
That’s because the package has to define the collections in order to work.
The good news is that you don’t need to define the collection yourself. They are already available for you (both client and server)  with the Vector.collection array
If you define a collection named, let’s say, “pages" inside the settings file, you will use that with Vector.collection[“pages”] or Vector.collection.pages

**Comment by handmadeadv** [comment]
Added a troubleshooting section on the website addressing this issue.

**Comment by scottspeidel** [comment]
Makes sense --thanks for the info.
